language: node_js
node_js:
  - 13
services:
  - docker
before_install:
  - echo "nothing needs to be done pre installation"

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests yet"

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed isongjosiah/udagram-api-feed:v5
  - docker tag udagram-api-user isongjosiah/udagram-api-user:v5
  - docker tag udagram-frontend isongjosiah/udagram-frontend:v5
  - docker tag reverse-proxy isongjosiah/reverse-proxy:v5

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push isongjosiah/udagram-api-feed:v5
  - docker push isongjosiah/udagram-api-user:v5
  - docker push isongjosiah/udagram-frontend:v5
  - docker push isongjosiah/reverse-proxy:v5
