apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: default
type: Opaque
data:
  AWS_ACCESS_KEY: YXdzX2FjY2Vzc19rZXlfaWQgPSBBS0lBVE5LMklSRVNCRllHSVVYVwphd3Nfc2VjcmV0X2FjY2Vz
  AWS_SECRET_ACCESS_KEY:  c19rZXkgPSA3d2FjdUpNdkEzR21yMDcrdDRtZlVObC96SXhNaVAzcWRra0NhM1VZCg==
