apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-deployment
  labels:
    app: reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: isongjosiah/reverse-proxy:v1
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: POSTGRES_HOST
            - name: AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: AWS_REGION
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: JWT_SECRET
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: POSTGRES_DB
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: config-env
                  key: URL
          ports:
            - containerPort: 80
